name: mtg
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^16.1.0
  flutter_dotenv: ^6.0.0
  dio: ^5.9.0
  window_manager: ^0.5.1

  bloc: ^9.1.0
  flutter_bloc: ^9.1.1
  equatable: 2.0.7
  get_it: ^9.2.0

  string_similarity: 2.1.1

  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  build_runner: ^2.4.9
  custom_lint: ^0.8.0

  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/jsons/
    - shorebird.yaml
