name: mtg
description: "A new Flutter project."

publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  go_router: ^13.2.4
  flutter_dotenv: ^5.1.0
  dio: ^5.4.3+1
  window_manager: ^0.3.8

  bloc: ^9.0.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.7
  get_it: ^8.0.3

  string_similarity: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  build_runner: ^2.4.9
  custom_lint: ^0.6.4

  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/jsons/
